services:
  # Контейнер с FastAPI
  app:
    build: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    volumes:
      - ./backend:/app
    networks:
      - localnetwork

  # Контейнер с PostgreSQL
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - localnetwork

networks:
  localnetwork:
    driver: bridge

volumes:
  postgres_data: {}
